### ISSUE TITLE
AttributeError: USE_RELU

### ISSUE THREAD

**Issue by CY-GAO222** [blueardour/AdelaiDet#4]
Traceback (most recent call last):
  File "/data2/gcy/202109/AdelaiDet/tools/train_net.py", line 219, in <module>
    args=(args,),
  File "/home/gcy/anaconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "/data2/gcy/202109/AdelaiDet/tools/train_net.py", line 201, in main
    trainer = Trainer(cfg)
  File "/home/gcy/anaconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 310, in __init__
    model = self.build_model(cfg)
  File "/home/gcy/anaconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 452, in build_model
    model = build_model(cfg)
  File "/home/gcy/anaconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/modeling/meta_arch/build.py", line 21, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/gcy/anaconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 257, in __init__
    self.backbone = build_backbone(cfg)
  File "/home/gcy/anaconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/modeling/backbone/build.py", line 31, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape)
  File "/data2/gcy/202109/AdelaiDet/adet/modeling/backbone/fpn.py", line 90, in build_fcos_resnet_fpn_backbone
    activation = cfg.MODEL.FPN.USE_RELU
  File "/home/gcy/anaconda3/envs/detectron2/lib/python3.7/site-packages/yacs-0.1.8-py3.7.egg/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: USE_RELU

**Comment by blueardour** [comment]
It seems that you are using the official Detectron2. Please use the dedicated one as instructed in the README file. For the quantization, every conv layer is followed by BN and ReLU layer.
